# Generated by Django 2.0.7 on 2018-07-27 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0004_jobs_send'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='send',
            name='date',
        ),
    ]
