# Generated by Django 2.0.7 on 2018-07-28 00:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0005_remove_send_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='send',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
