# Generated by Django 2.0.7 on 2018-07-28 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0006_send_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='send',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
