# Generated by Django 2.0.7 on 2018-07-28 02:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0007_auto_20180728_0117'),
    ]

    operations = [
        migrations.AddField(
            model_name='send',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
